server:
  port: 8080

spring:
  application:
    name: pagamento-ms
  datasource:
    url: jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true
    username: root
    password: vini4222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        spring:
          datasource:
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8081/eureka'
